spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-postgres.yml
    enabled: true
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/final
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
logging:
  pattern:
    console: >
      %d{yyyy-MM-dd HH:mm:ss} - %highlight(%-5level) - %cyan(%logger{36}) - %msg%n
